/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "var(--md-on-background)",
        "tertiary-fixed-dim": "var(--md-tertiary-fixed-dim)",
        "secondary-fixed-dim": "var(--md-secondary-fixed-dim)",
        "inverse-surface": "var(--md-inverse-surface)",
        "error-container": "var(--md-error-container)",
        "inverse-primary": "var(--md-inverse-primary)",
        "secondary-fixed": "var(--md-secondary-fixed)",
        "on-primary-fixed-variant": "var(--md-on-primary-fixed-variant)",
        "surface-variant": "var(--md-surface-variant)",
        "on-primary": "var(--md-on-primary)",
        "surface-container-high": "var(--md-surface-container-high)",
        "surface-bright": "var(--md-surface-bright)",
        "on-secondary": "var(--md-on-secondary)",
        "inverse-on-surface": "var(--md-inverse-on-surface)",
        "primary-fixed-dim": "var(--md-primary-fixed-dim)",
        "secondary-container": "var(--md-secondary-container)",
        "tertiary-container": "var(--md-tertiary-container)",
        "on-secondary-container": "var(--md-on-secondary-container)",
        "on-error-container": "var(--md-on-error-container)",
        "on-surface-variant": "var(--md-on-surface-variant)",
        "surface": "var(--md-surface)",
        "outline-variant": "var(--md-outline-variant)",
        "primary-container": "var(--md-primary-container)",
        "tertiary": "var(--md-tertiary)",
        "on-secondary-fixed": "var(--md-on-secondary-fixed)",
        "on-tertiary-fixed-variant": "var(--md-on-tertiary-fixed-variant)",
        "on-primary-container": "var(--md-on-primary-container)",
        "surface-container-highest": "var(--md-surface-container-highest)",
        "surface-dim": "var(--md-surface-dim)",
        "on-tertiary-container": "var(--md-on-tertiary-container)",
        "on-tertiary-fixed": "var(--md-on-tertiary-fixed)",
        "surface-tint": "var(--md-surface-tint)",
        "surface-container-low": "var(--md-surface-container-low)",
        "outline": "var(--md-outline)",
        "on-surface": "var(--md-on-surface)",
        "on-error": "var(--md-on-error)",
        "on-tertiary": "var(--md-on-tertiary)",
        "primary": "var(--md-primary)",
        "tertiary-fixed": "var(--md-tertiary-fixed)",
        "primary-fixed": "var(--md-primary-fixed)",
        "background": "var(--md-background)",
        "secondary": "var(--md-secondary)",
        "error": "var(--md-error)",
        "on-secondary-fixed-variant": "var(--md-on-secondary-fixed-variant)",
        "surface-container": "var(--md-surface-container)",
        "surface-container-lowest": "var(--md-surface-container-lowest)",
        "on-primary-fixed": "var(--md-on-primary-fixed)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "32px",
        "gutter": "24px",
        "unit": "4px",
        "container-max": "1280px",
        "unit-xs": "4px",
        "margin-desktop": "64px",
        "unit-lg": "24px",
        "margin-mobile": "20px",
        "unit-xl": "48px",
        "unit-sm": "8px",
        "unit-md": "16px"
      },
      fontFamily: {
        "headline-lg": ["Archivo Narrow"],
        "label-mono": ["Space Mono"],
        "headline-md": ["Archivo Narrow"],
        "headline-lg-mobile": ["Archivo Narrow"],
        "headline-xl": ["Archivo Narrow"],
        "h1-mobile": ["Sora"],
        "body-lg": ["Inter"],
        "h1": ["Sora"],
        "h3": ["Sora"],
        "h2": ["Sora"],
        "label-bold": ["Inter"],
        "body-md": ["Inter"],
        "caption": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["40px", { "lineHeight": "1.1", "letterSpacing": "-0.01em", "fontWeight": "800" }],
        "label-mono": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.1", "fontWeight": "800" }],
        "headline-xl": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "h1-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "h1": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "h3": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "h2": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-bold": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
